### ISSUE TITLE
Omitted some lakes from MRB extrapolation

### ISSUE THREAD

**Issue by jbeaulie** [USEPA/climateBenefits#6]
In the process of creating the MRB study site map I spent some time reviewing your extrapolation code.  I believe I found one minor error.  In get_ghg_waterbodies_in_mrb.R you filtered the .gpkg that I provided to only include observations that have a value for the globalid field:

`## keep only columns needed for filtering to watershed` 
`national %<>% 
  dplyr::select(globalid, stusps) %>% 
  filter(!is.na(globalid))`

Only polygons derived from the National Wetland Inventory have a value for the `globalid` field.  The other polygons in the .gpkg were derived from NHDPlusV2 and have a value for the `comid` field, but not `globalid`.  We want to retain polygons from both sources.  I believe the code should read:
`national %<>% 
  dplyr::select(comid, globalid, stusps)`

Then in get_reductions_in_mrb_ch4.R we use the following code to select waterbodies contained within the MRB watershed:
`## read all waterbodies from ghgrp, filter to those in mississippi river basin`
`data =`
  `read_sf('store/climateBenefits.gpkg') %>%`
  `dplyr::select(globalid, comid, stusps, climate, subtype, area_ha_new, co2.tonnes.ha.y.2021, ch4.tonnes.ha.y.2021) %>%`
  `filter((comid %in% unique(na.omit(mrb.waterbodies$comid)))| # get NHD waterbodies` 
          `(globalid %in% unique(na.omit(mrb.waterbodies$globalid)))) # get NWI waterbodies`

Your code omits 27,548 NHD polygons from consideration when filtering the .gpkg against the MRB watershed boundary.  At the end of the day, the reduction in CH4 emissions from MRB increases from 93,000 metric tons to 103,404 metric tons, a rather minor change.

Do you have any recollection of us deciding to omit the NHD polygons?  We might have done this for a reason, but I can't think of any now.

If we want to update the manuscript, I can revise everything except this statement:
The net present value of the monetized climate benefits over the first forty years of the program (2035-2075) are then $9.6 billion (2020USD, 2% discount rate),...
I'll need help with that calculation.

**Comment by bryanparthum** [comment]
@jbeaulie, this is just the result of a miscommunication about what the differences were between the `globalid` and the `comid`. I recall asking why there were so many `na`'s and if we should be using the `globalid`, you said that is the correct one, but I likely didn't understand that you meant we should use both. My mistake for not communicating clearly. The filtering was intentional, but I didn't realize that we should join on both. I think I just didn't understand the difference between the types of waterbodies. 

Thank you for catching and correcting that.

I updated the stream of climate benefits for the MARB to `103,404` CH4-t, the new total over the 40 years (2035-2075) is `10,572,092,000`, or $10.6 billion for that sentence.

**Comment by jbeaulie** [comment]
@bryanparthum Great, I made the changes to your script and the manuscript.
